### ISSUE TITLE
Error (use-package): general/:config: Symbol’s value as variable is void: <<general-config>>

### ISSUE THREAD

**Issue by hongyi-zhao** [progfolio/.emacs.d#1]
I try to test [the `general` package configuration used by you](https://github.com/progfolio/.emacs.d#general-key-bindings):
```emacs-lisp
(use-package general
  :demand t
  :config
  (general-override-mode)
  (general-auto-unbind-keys)
  <<general-config>>
  )
```
But Emacs gives the following Warnings:

`Error (use-package): general/:config: Symbol’s value as variable is void: <<general-config>>`

Any hints for this problem?

Regards,
HZ

**Comment by progfolio** [comment]
My init.org is a literate org file. `<<reference>>` is Org's noweb syntax. It is not valid elisp.
